name: Upload test report

on:
  push:
    branches: [ main ]

jobs:

  upload:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore tools
      run: dotnet tool restore

    - name: Cake Action
      run: dotnet cake ./build.cake --Target UploadTestReport
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
